In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os, json

CHECKPOINT_DIR = "/content/drive/MyDrive/codellama-coding-chat/checkpoint-250"

if os.path.exists(CHECKPOINT_DIR):
    files = os.listdir(CHECKPOINT_DIR)
    print(f"✅ Checkpoint found: {len(files)} files")
else:
    print("❌ Checkpoint not found")
    raise SystemExit

Mounted at /content/drive
✅ Checkpoint found: 12 files

In [2]:
import shutil

local_dir = "./codellama-coding-chat/checkpoint-250"
os.makedirs("./codellama-coding-chat", exist_ok=True)

if os.path.exists(local_dir):
    print("Local checkpoint already exists, skipping copy")
else:
    shutil.copytree(CHECKPOINT_DIR, local_dir)
    print("✅ Copied to local")

RESUME_CHECKPOINT = local_dir
print(f"Using: {RESUME_CHECKPOINT}")

✅ Copied to local
Using: ./codellama-coding-chat/checkpoint-250

In [3]:
!pip install -q transformers datasets accelerate peft bitsandbytes trl

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 12.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 528.8/528.8 kB 26.7 MB/s eta 0:00:00

In [4]:
import torch
import os
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    BitsAndBytesConfig,
    TrainerCallback,
    Trainer,
    DataCollatorForLanguageModeling
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, PeftModel
from datasets import load_dataset, concatenate_datasets

print(f"✅ CUDA: {torch.cuda.is_available()}")
print(f"✅ GPU: {torch.cuda.get_device_name(0)}")

✅ CUDA: True
✅ GPU: Tesla T4

In [5]:
MODEL_NAME = "codellama/CodeLlama-7b-Instruct-hf"
OUTPUT_DIR = "./codellama-coding-chat"
RESUME_CHECKPOINT = "./codellama-coding-chat/checkpoint-250"

MAX_SEQ_LENGTH = 512
CODE_SAMPLES = 3000
CHAT_SAMPLES = 1000
MAX_STEPS = 500
SAVE_STEPS = 100

print(f"Resuming from: {RESUME_CHECKPOINT}")
print(f"Target steps: {MAX_STEPS}")

Resuming from: ./codellama-coding-chat/checkpoint-250
Target steps: 500

In [6]:
print("Loading datasets...")

code_dataset = load_dataset("iamtarun/python_code_instructions_18k_alpaca", split="train")
code_dataset = code_dataset.shuffle(seed=42).select(range(min(CODE_SAMPLES, len(code_dataset))))
print(f"✅ Code: {len(code_dataset)}")

chat_dataset = load_dataset("mlabonne/orpo-dpo-mix-40k", split="train")
chat_dataset = chat_dataset.shuffle(seed=42).select(range(min(CHAT_SAMPLES, len(chat_dataset))))
print(f"✅ Chat: {len(chat_dataset)}")

Loading datasets...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/905 [00:00<?, ?B/s]

data/train-00000-of-00001-8b6e212f3e1ece(…):   0%|          | 0.00/11.4M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/18612 [00:00<?, ? examples/s]

✅ Code: 3000

README.md: 0.00B [00:00, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/127M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/44245 [00:00<?, ? examples/s]

✅ Chat: 1000

In [7]:
def format_code(example):
    instruction = example.get('prompt', example.get('instruction', ''))
    input_text = example.get('input', '')
    output = example.get('completion', example.get('output', ''))
    prompt = f"{instruction}\n\nInput: {input_text}" if input_text else instruction
    return f"[INST] {prompt.strip()} [/INST] {output.strip()}"

def format_chat(example):
    prompt = example.get('prompt', example.get('question', example.get('instruction', '')))
    response = example.get('chosen', example.get('response', example.get('answer', example.get('output', ''))))
    if isinstance(response, list):
        response = response[0] if response else ""
    return f"[INST] {prompt.strip()} [/INST] {str(response).strip()}"

code_formatted = code_dataset.map(lambda x: {"text": format_code(x)}, remove_columns=code_dataset.column_names)
chat_formatted = chat_dataset.map(lambda x: {"text": format_chat(x)}, remove_columns=chat_dataset.column_names)
full_dataset = concatenate_datasets([code_formatted, chat_formatted]).shuffle(seed=42)
print(f"✅ Total: {len(full_dataset)} examples")

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

✅ Total: 4000 examples

In [8]:
print("Loading model...")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Load base model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
)
model.config.use_cache = False
model = prepare_model_for_kbit_training(model)

# Apply SAME LoRA config as original training
lora_config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

print(f"✅ Model ready")
print(f"💾 GPU: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

Loading model...

config.json:   0%|          | 0.00/646 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/411 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

trainable params: 79,953,920 || all params: 6,818,500,608 || trainable%: 1.1726
✅ Model ready
💾 GPU: 4.73 GB

In [9]:
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    optim="paged_adamw_8bit",
    learning_rate=2e-4,
    max_grad_norm=0.3,
    warmup_steps=15,
    lr_scheduler_type="cosine",
    logging_steps=10,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    fp16=True,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={'use_reentrant': False},
    report_to="none",
    max_steps=MAX_STEPS,
)

In [10]:
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_SEQ_LENGTH,
        padding="max_length"
    )

print("Tokenizing...")
tokenized_dataset = full_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=full_dataset.column_names
)
print(f"✅ {len(tokenized_dataset)} examples tokenized")

Tokenizing...

Map:   0%|          | 0/4000 [00:00<?, ? examples/s]

✅ 4000 examples tokenized

In [11]:
class ProgressCallback(TrainerCallback):
    def on_save(self, args, state, control, **kwargs):
        with open(os.path.join(args.output_dir, "latest_checkpoint.txt"), "w") as f:
            f.write(f"{state.global_step}")
        print(f"💾 Checkpoint saved: Step {state.global_step}")

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator,
    callbacks=[ProgressCallback],
)

print("✅ Trainer ready")
print(f"Resuming from checkpoint: {RESUME_CHECKPOINT}")

✅ Trainer ready
Resuming from checkpoint: ./codellama-coding-chat/checkpoint-250

In [12]:
print("🔥 RESUMING TRAINING from step 250 → 500")
print(f"GPU: {torch.cuda.get_device_name(0)}")
print("=" * 50)

trainer.train(resume_from_checkpoint=RESUME_CHECKPOINT)

print("=" * 50)
print("✅ Training complete!")

🔥 RESUMING TRAINING from step 250 → 500
GPU: Tesla T4
==================================================

Warning: The following arguments do not match the ones in the `trainer_state.json` within the checkpoint directory:
	logging_steps: 10 (from args) != 25 (from trainer_state.json)
	save_steps: 100 (from args) != 250 (from trainer_state.json)

💾 Checkpoint saved: Step 500
==================================================
✅ Training complete!

In [15]:
import torch
import psutil
import os

# GPU Info
print("=" * 40)
print("GPU")
print("=" * 40)
if torch.cuda.is_available():
    print(f"Name:        {torch.cuda.get_device_name(0)}")
    total = torch.cuda.get_device_properties(0).total_memory / 1e9
    used = torch.cuda.memory_allocated() / 1e9
    free = total - used
    print(f"Total VRAM:  {total:.2f} GB")
    print(f"Used VRAM:   {used:.2f} GB")
    print(f"Free VRAM:   {free:.2f} GB")

# CPU Info
print("\n" + "=" * 40)
print("CPU")
print("=" * 40)
print(f"Cores:       {psutil.cpu_count(logical=False)} physical, {psutil.cpu_count()} logical")
print(f"Usage:       {psutil.cpu_percent()}%")

# RAM Info
print("\n" + "=" * 40)
print("RAM")
print("=" * 40)
ram = psutil.virtual_memory()
print(f"Total:       {ram.total / 1e9:.2f} GB")
print(f"Used:        {ram.used / 1e9:.2f} GB")
print(f"Free:        {ram.available / 1e9:.2f} GB")
print(f"Usage:       {ram.percent}%")

# Disk Info
print("\n" + "=" * 40)
print("DISK")
print("=" * 40)
disk = psutil.disk_usage('/')
print(f"Total:       {disk.total / 1e9:.2f} GB")
print(f"Used:        {disk.used / 1e9:.2f} GB")
print(f"Free:        {disk.free / 1e9:.2f} GB")
print(f"Usage:       {disk.percent}%")

========================================
GPU
========================================
Name:        Tesla T4
Total VRAM:  15.64 GB
Used VRAM:   4.92 GB
Free VRAM:   10.72 GB

========================================
CPU
========================================
Cores:       1 physical, 2 logical
Usage:       61.0%

========================================
RAM
========================================
Total:       13.61 GB
Used:        2.68 GB
Free:        10.58 GB
Usage:       22.2%

========================================
DISK
========================================
Total:       120.94 GB
Used:        62.98 GB
Free:        57.95 GB
Usage:       52.1%

In [14]:
import shutil

# Save final adapter
model.save_pretrained("./codellama-coding-chat-final")
tokenizer.save_pretrained("./codellama-coding-chat-final")
print("✅ Final adapter saved locally")

# Copy to Drive
drive_dest = "/content/drive/MyDrive/codellama-coding-chat-final"
os.makedirs(drive_dest, exist_ok=True)
shutil.copytree("./codellama-coding-chat-final", drive_dest, dirs_exist_ok=True)
print(f"✅ Saved to Drive: {drive_dest}")

✅ Final adapter saved locally
✅ Saved to Drive: /content/drive/MyDrive/codellama-coding-chat-final

In [16]:
!pip install -q huggingface_hub gradio

In [17]:
from huggingface_hub import login

HF_TOKEN = "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"  # paste your token here
HF_USERNAME = "affan3671"  # your HF username
MODEL_REPO = f"{HF_USERNAME}/codellama-coding-chat"

login(token=HF_TOKEN)
print("✅ Logged in to Hugging Face")

✅ Logged in to Hugging Face

In [18]:
import os

# Save adapter + tokenizer locally
model.save_pretrained("./codellama-coding-chat-final")
tokenizer.save_pretrained("./codellama-coding-chat-final")

files = os.listdir("./codellama-coding-chat-final")
print(f"✅ Saved locally: {files}")

✅ Saved locally: ['tokenizer.json', 'adapter_config.json', 'adapter_model.safetensors', 'chat_template.jinja', 'tokenizer_config.json', 'README.md']

In [22]:
# Skip merge, just upload the LoRA adapter
# It's only 450MB instead of 13GB and works fine

from huggingface_hub import HfApi
import os

api = HfApi()

api.create_repo(
    repo_id=MODEL_REPO,
    token=HF_TOKEN,
    exist_ok=True,
    private=False
)

print("Uploading adapter (only ~450MB, much faster)...")
api.upload_folder(
    folder_path="./codellama-coding-chat-final",
    repo_id=MODEL_REPO,
    token=HF_TOKEN,
)

print(f"✅ Adapter uploaded!")
print(f"🔗 https://huggingface.co/{MODEL_REPO}")

Uploading adapter (only ~450MB, much faster)...

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...adapter_model.safetensors:   0%|          |  557kB /  320MB

✅ Adapter uploaded!
🔗 https://huggingface.co/affan3671/codellama-coding-chat

In [24]:
app_code = '''
import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel

BASE_MODEL = "codellama/CodeLlama-7b-Instruct-hf"
ADAPTER = "''' + MODEL_REPO + '''"

print("Loading model...")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
tokenizer.pad_token = tokenizer.eos_token

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
)

model = PeftModel.from_pretrained(base_model, ADAPTER)
model.eval()
print("✅ Model ready!")

def generate(message, history, max_tokens, temperature):
    prompt = f"[INST] {message} [/INST]"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=int(max_tokens),
            temperature=float(temperature),
            do_sample=True,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    response = response.split("[/INST]")[-1].strip()
    return response

demo = gr.ChatInterface(
    fn=generate,
    title="🤖 CodeLlama Coding Chat",
    description="Fine-tuned CodeLlama-7B for coding and general chat.",
    examples=[
        ["Write a Python function to reverse a string"],
        ["Explain what machine learning is in simple terms"],
        ["How do I fix an IndexError in Python?"],
        ["Write a SQL query to find duplicate emails"],
        ["What is the difference between list and tuple?"],
    ],
    additional_inputs=[
        gr.Slider(64, 1024, value=512, step=64, label="Max Tokens"),
        gr.Slider(0.1, 1.0, value=0.7, step=0.1, label="Temperature"),
    ],
    theme=gr.themes.Soft(),
)

demo.launch()
'''

with open("app.py", "w") as f:
    f.write(app_code)

print("✅ app.py created")

✅ app.py created

In [25]:
requirements = """transformers
accelerate
bitsandbytes
peft
torch
gradio
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("✅ requirements.txt created")

✅ requirements.txt created

In [27]:
from huggingface_hub import HfApi

SPACE_REPO = "affan3671/codellama-chat-ui"

app_code = '''
import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
import os

BASE_MODEL = "codellama/CodeLlama-7b-Instruct-hf"
ADAPTER = "affan3671/codellama-coding-chat"

# Check if GPU is available
HAS_GPU = torch.cuda.is_available()
print(f"GPU available: {HAS_GPU}")

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
tokenizer.pad_token = tokenizer.eos_token

print("Loading model...")
if HAS_GPU:
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
    )
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.float16,
    )
    model = PeftModel.from_pretrained(base_model, ADAPTER)
else:
    # CPU mode - load smaller/lighter
    base_model = AutoModelForCausalLM.from_pretrained(
        BASE_MODEL,
        device_map="cpu",
        torch_dtype=torch.float32,
        low_cpu_mem_usage=True,
    )
    model = PeftModel.from_pretrained(base_model, ADAPTER)

model.eval()
print("✅ Model ready!")

def generate(message, history, max_tokens, temperature):
    if not message.strip():
        return "Please enter a message."

    prompt = f"[INST] {message} [/INST]"
    device = "cuda" if HAS_GPU else "cpu"
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=int(max_tokens),
            temperature=float(temperature),
            do_sample=True,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    response = response.split("[/INST]")[-1].strip()
    return response

demo = gr.ChatInterface(
    fn=generate,
    title="🤖 CodeLlama Coding Chat",
    description="Fine-tuned CodeLlama-7B for coding and general chat. ⚠️ Running on CPU — responses may take 1-2 mins.",
    examples=[
        ["Write a Python function to reverse a string"],
        ["Explain what machine learning is in simple terms"],
        ["How do I fix an IndexError in Python?"],
        ["Write a SQL query to find duplicate emails"],
    ],
    additional_inputs=[
        gr.Slider(64, 512, value=256, step=64, label="Max Tokens"),
        gr.Slider(0.1, 1.0, value=0.7, step=0.1, label="Temperature"),
    ],
    theme=gr.themes.Soft(),
)

demo.launch()
'''

with open("app.py", "w") as f:
    f.write(app_code)

# Upload updated app.py
api = HfApi()
api.upload_file(
    path_or_fileobj="app.py",
    path_in_repo="app.py",
    repo_id=SPACE_REPO,
    repo_type="space",
    token=HF_TOKEN,
)

print("✅ Updated app.py uploaded!")
print("⏳ Space will rebuild in 2-3 mins")
print(f"🔗 https://huggingface.co/spaces/{SPACE_REPO}")

✅ Updated app.py uploaded!
⏳ Space will rebuild in 2-3 mins
🔗 https://huggingface.co/spaces/affan3671/codellama-chat-ui

In [28]:
!pip install -q pyngrok gradio

In [29]:
from pyngrok import ngrok

NGROK_TOKEN = "2Pe85Ujp1ofCMoYiApD9uZjkWw7_6XVrpzw4mwJNt9gUGYQzw"  # paste your token here

ngrok.set_auth_token(NGROK_TOKEN)
print("✅ Ngrok authenticated")

✅ Ngrok authenticated

In [31]:
import torch
import gc

# Delete training model from memory
try:
    del model
    del base_model
    del peft_model
    del merged
    del trainer
except:
    pass

# Force garbage collection
gc.collect()
torch.cuda.empty_cache()

print(f"✅ GPU cleared!")
print(f"💾 GPU free: {(torch.cuda.get_device_properties(0).total_memory - torch.cuda.memory_allocated()) / 1e9:.2f} GB")

✅ GPU cleared!
💾 GPU free: 1.33 GB

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from peft import PeftModel
import torch

BASE_MODEL = "codellama/CodeLlama-7b-Instruct-hf"
ADAPTER = "affan3671/codellama-coding-chat"

print("Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
tokenizer.pad_token = tokenizer.eos_token

print("Loading model...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
    llm_int8_enable_fp32_cpu_offload=True,  # ← fixes the error
)

base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
)

print("Loading adapter...")
inference_model = PeftModel.from_pretrained(base_model, ADAPTER)
inference_model.eval()

print(f"✅ Model ready!")
print(f"💾 GPU used: {torch.cuda.memory_allocated() / 1e9:.2f} GB")

Loading tokenizer...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
`torch_dtype` is deprecated! Use `dtype` instead!

Loading model...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Loading adapter...

adapter_config.json: 0.00B [00:00, ?B/s]

adapter_model.safetensors:   0%|          | 0.00/320M [00:00<?, ?B/s]

✅ Model ready!
💾 GPU used: 4.21 GB

In [2]:
import gradio as gr
from pyngrok import ngrok

def generate(message, history, max_tokens, temperature):
    if not message.strip():
        return "Please enter a message."

    prompt = f"[INST] {message} [/INST]"
    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")

    with torch.no_grad():
        outputs = inference_model.generate(
            **inputs,
            max_new_tokens=int(max_tokens),
            temperature=float(temperature),
            do_sample=True,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer.eos_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    response = response.split("[/INST]")[-1].strip()
    return response

demo = gr.ChatInterface(
    fn=generate,
    title="🤖 CodeLlama Coding Chat",
    description="Fine-tuned CodeLlama-7B | Ask me anything about coding!",
    examples=[
        ["Write a Python function to reverse a string"],
        ["Explain what machine learning is"],
        ["How do I fix an IndexError in Python?"],
        ["Write a SQL query to find duplicate emails"],
    ],
    additional_inputs=[
        gr.Slider(64, 512, value=256, step=64, label="Max Tokens"),
        gr.Slider(0.1, 1.0, value=0.7, step=0.1, label="Temperature"),
    ],
    theme=gr.themes.Soft(),
)

# Kill old tunnels
ngrok.kill()

# Launch
demo.launch(server_port=7860, share=False, quiet=True)

# Create public link
public_url = ngrok.connect(7860)
print("=" * 50)
print("🎉 YOUR CHAT UI IS LIVE!")
print(f"🔗 Public URL: {public_url}")
print("=" * 50)

/usr/local/lib/python3.12/dist-packages/gradio/chat_interface.py:347: UserWarning: The 'tuples' format for chatbot messages is deprecated and will be removed in a future version of Gradio. Please set type='messages' instead, which uses openai-style 'role' and 'content' keys.
  self.chatbot = Chatbot(

==================================================
🎉 YOUR CHAT UI IS LIVE!
🔗 Public URL: NgrokTunnel: "https://a79b-34-168-229-234.ngrok-free.app" -> "http://localhost:7860"
==================================================

In [5]:
import os

# Search for the notebook
result = os.popen('find /content -name "*.ipynb" 2>/dev/null').read()
print("Found notebooks:")
print(result)

Found notebooks: